spring.application.name=atomicx
spring.datasource.url=jdbc:postgresql://localhost:5432/atomicx
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true


# Max number of active request processing threads
server.tomcat.threads.max=500
# Minimum number of threads always kept alive
server.tomcat.threads.min-spare=50
# Max number of connections the server accepts and queues when threads are full
server.tomcat.accept-count=100

# Increase pool size (don't go too high, or you'll overwhelm the DB)
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
# How long a thread will wait for a connection before failing
spring.datasource.hikari.connection-timeout=20000
# Helps identify "leaked" connections during heavy load
spring.datasource.hikari.leak-detection-threshold=2000

# Set logging to WARN or ERROR for the load test
logging.level.root=WARN
logging.level.org.springframework.web=INFO
# Disable Hibernate SQL logging if enabled
spring.jpa.show-sql=false

app.system.id=550e8400-e29b-41d4-a716-446655440000
